(function () {
    /*-- begin iify--*/
'use strict';

/*
    This module is a stub for so the template cache has a module to belong to
    The template cache is generated by a gulp task
*/
angular
    .module('templates', []);

/*-- end iify--*/
}());